image: python:latest

stages:
    - coverage

coverage:
    stage: coverage
    tags:
        - docker
    script: |
        pip install pytest
        pip install pytest-cov
        git diff --no-commit-id --name-only -r $CI_COMMIT_SHA | cat
        pytest --cov=src/ --cov-report xml:coverage/coverage.xml
    artifacts:
        reports:
            cobertura: coverage/coverage.xml