image: python:latest

stages:
    - coverage

coverage:
    stage: coverage
    tags:
        - docker
    script: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=src/ --cov-report xml:coverage/coverage.xml
    artifacts:
        reports:
            cobertura: coverage/coverage.xml