image: python:latest

stages:
    - coverage

coverage:
    stage: coverage
    tags:
        - docker
    script: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=src/ --cov-report xml:tools/coverage/coverage.xml
    artifacts:
        reports:
            cobertura: tools/coverage/coverage.xml