image: python:latest

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
    - coverage
    - test

code_quality:
    artifacts:
        paths: [gl-code-quality-report.json]

coverage:
    stage: coverage
    tags:
        - docker
    script: |
        pip install -r requirements.txt
        python -m pytest --cov=src/ --cov-report xml:tools/coverage/coverage.xml 
    artifacts:
        reports:
            cobertura: tools/coverage/coverage.xml